#include <iostream>
#include <fstream>
#include "Color.hpp"
#include "Image2D.hpp"
#include "Image2DWriter.hpp"

using namespace std;

int main( int argc, char** argv )
{
    typedef Image2D<Color> ColorImage2D;
    typedef ColorImage2D::Iterator Iterator;
    typedef ColorImage2D::ConstIterator ConstIterator;
    //ColorImage2D img( 8, 8, Color(0, 255, 0) ); // imagette 8x8 remplie de couleur verte
    // test iterator
    /*ColorImage2D img( 256, 256, Color(0, 0, 0) ); // imagette 256x256 remplie de couleur verte
    Iterator it = img.begin();
    for ( int y = 0; y < img.h(); ++y )
    {
        for ( int x = 0; x < img.w(); ++x )

            // *it++ = Color( y, x, (2*x+2*y) % 256 );
    }*/
    /*
    std::ofstream output( "colors.ppm"); // ios::binary for Windows system
    output << "P6" << std::endl; // PPM raw
    output << "# Generated by You !" << std::endl;
    output << img.w() << " " << img.h() << std::endl;
    output << "255" << std::endl;
     */

    /*
    for ( Iterator it = img.begin(), itE = img.end(); it != itE; ++it ) // (*)
    {
        Color c = *it;
        output << c.red << c.green << c.blue;
    }
     */
    /*
    const ColorImage2D& cimg = img; // Vue "constante" sur l'image img.
    for ( ConstIterator cit = cimg.begin(), itE = cimg.end(); cit != itE; ++cit ) // (*)
    {
        Color c = *cit;
        output << c.red << c.green << c.blue;
    }
    output.close();
     */
    /*ofstream output( "colors.ppm" );
    bool ok2 = Image2DWriter<Color>::write( img, output, false );
    if ( !ok2 ) {
        std::cerr << "Error writing output file." << std::endl;
        return 1;
    }
    output.close();*/

    //test lire image et réécrire
    //test lire une image PGM et l'écrire
    if(argv[1] && argv[2]) {
        ColorImage2D img;
        ifstream input(argv[1]);
        try {
            Image2DReader<Color>::read(img, input);
        }
        catch (char const *msg) {
            std::cerr << "Exception: " << msg << std::endl;
        }
        catch (...) {
            std::cerr << "Exception inconnue." << std::endl;
        }
        input.close();

        //  export
        ofstream output(argv[2]);
        Image2DWriter<Color>::write(img, output, false);
        output.close();
        std::cout << std::endl;

    }
    else{
        std::cerr << "Pas de argv[1] et/ou argv[2], attendus : fichier_d_entree "
                  << "fichier_de_sortie \"double-brighness\" ou \"filtrage-median {k}\" ou \"egalisation\" ";
    }


    return 0;
}